# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configure.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configure(object):
    def setupUi(self, Configure):
        Configure.setObjectName("Configure")
        Configure.resize(226, 231)
        self.label = QtWidgets.QLabel(Configure)
        self.label.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Configure)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Configure)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Configure)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Configure)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 61, 21))
        self.label_5.setObjectName("label_5")
        self.comport = QtWidgets.QComboBox(Configure)
        self.comport.setGeometry(QtCore.QRect(110, 20, 69, 22))
        self.comport.setObjectName("comport")
        self.BaudRate = QtWidgets.QComboBox(Configure)
        self.BaudRate.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.BaudRate.setObjectName("BaudRate")
        self.Parity = QtWidgets.QComboBox(Configure)
        self.Parity.setGeometry(QtCore.QRect(110, 80, 69, 22))
        self.Parity.setObjectName("Parity")
        self.databit = QtWidgets.QComboBox(Configure)
        self.databit.setGeometry(QtCore.QRect(110, 110, 69, 22))
        self.databit.setObjectName("databit")
        self.stopbit = QtWidgets.QComboBox(Configure)
        self.stopbit.setGeometry(QtCore.QRect(110, 140, 69, 22))
        self.stopbit.setObjectName("stopbit")
        self.pushButton = QtWidgets.QPushButton(Configure)
        self.pushButton.setGeometry(QtCore.QRect(70, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.ModbusType = QtWidgets.QComboBox(Configure)
        self.ModbusType.setGeometry(QtCore.QRect(110, 170, 69, 22))
        self.ModbusType.setObjectName("ModbusType")
        self.label_6 = QtWidgets.QLabel(Configure)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 61, 21))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Configure)
        QtCore.QMetaObject.connectSlotsByName(Configure)

    def retranslateUi(self, Configure):
        _translate = QtCore.QCoreApplication.translate
        Configure.setWindowTitle(_translate("Configure", "Configure"))
        self.label.setText(_translate("Configure", "COM port"))
        self.label_2.setText(_translate("Configure", "Baud Rate"))
        self.label_3.setText(_translate("Configure", "Parity"))
        self.label_4.setText(_translate("Configure", "Data bit"))
        self.label_5.setText(_translate("Configure", "Stop bit"))
        self.pushButton.setText(_translate("Configure", "Close"))
        self.label_6.setText(_translate("Configure", "MODBUS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Configure = QtWidgets.QWidget()
    ui = Ui_Configure()
    ui.setupUi(Configure)
    Configure.show()
    sys.exit(app.exec_())
