# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Terminal_ui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(795, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Configure = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Configure.sizePolicy().hasHeightForWidth())
        self.Configure.setSizePolicy(sizePolicy)
        self.Configure.setObjectName("Configure")
        self.gridLayout.addWidget(self.Configure, 0, 0, 1, 1)
        self.Clear = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear.sizePolicy().hasHeightForWidth())
        self.Clear.setSizePolicy(sizePolicy)
        self.Clear.setObjectName("Clear")
        self.gridLayout.addWidget(self.Clear, 0, 4, 1, 1)
        self.Timestamp = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Timestamp.sizePolicy().hasHeightForWidth())
        self.Timestamp.setSizePolicy(sizePolicy)
        self.Timestamp.setObjectName("Timestamp")
        self.gridLayout.addWidget(self.Timestamp, 0, 3, 1, 1)
        self.log = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        self.log.setObjectName("log")
        self.gridLayout.addWidget(self.log, 0, 2, 1, 1)
        self.Connect = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connect.sizePolicy().hasHeightForWidth())
        self.Connect.setSizePolicy(sizePolicy)
        self.Connect.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Connect.setObjectName("Connect")
        self.gridLayout.addWidget(self.Connect, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.OutputText = QtWidgets.QTextBrowser(MainWindow)
        self.OutputText.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputText.sizePolicy().hasHeightForWidth())
        self.OutputText.setSizePolicy(sizePolicy)
        self.OutputText.setMouseTracking(False)
        self.OutputText.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.OutputText.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.OutputText.setReadOnly(True)
        self.OutputText.setObjectName("OutputText")
        self.gridLayout_2.addWidget(self.OutputText, 1, 0, 1, 1)
        self.command = QtWidgets.QLineEdit(MainWindow)
        self.command.setObjectName("command")
        self.gridLayout_2.addWidget(self.command, 2, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Terminal"))
        self.Configure.setText(_translate("MainWindow", "Configure"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.Timestamp.setText(_translate("MainWindow", "TimeStamp"))
        self.log.setText(_translate("MainWindow", "Log to file"))
        self.Connect.setText(_translate("MainWindow", "Disconnect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
